### ISSUE TITLE
Fluid Item Transformation - Item Duplication with Mekanism

### ISSUE THREAD

**Issue by Spolonus282** [NovaMachina-Mods/ExNihiloSequentia-Mekanism#5]
**Describe the bug**
Items inserted into a barrel using a Mekanism logistical transporter will not be consumed but will still output resources.

**To Reproduce**
1. Place a barrel, fed with water
2. Place a logistical transporter above it, feeding from a hopper with a single piece of dust in it.
3. Clay will appear in the barrel, and as long as water is fed into the barrel, will continue to make clay from the single dust.

**Expected behavior**
The dust should be extracted from the hopper, and clay is produced once.

**Screenshots**
![2021-04-15_20 54 16](https://user-images.githubusercontent.com/31666841/114956730-7646cb00-9e2d-11eb-929d-598740ef15c7.png)

![2021-04-15_20 57 45](https://user-images.githubusercontent.com/31666841/114956741-7d6dd900-9e2d-11eb-8b0b-f8b026e4b9eb.png)

![2021-04-15_20 57 24](https://user-images.githubusercontent.com/31666841/114956750-8363ba00-9e2d-11eb-8b67-b1e616df040f.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.3
Ex Nihilo: Sequentia Version: 1.16-2.0.2.3

**Additional context**
Any tile entity above the logistical transporter will work, a hopper was the example because that was how I found the bug.

**Comment by NovaMachina** [comment]
Should be fixed in latest version of Ex Nihilo: Sequentia.
